# you can disable an alarm notification by setting the 'to' line to: silent

# -----------------------------------------------------------------------------
# low disk space

# checking the latest collected values
# raise an alarm if the disk is low on
# available disk space

    template: disk_space_usage
          on: disk.space
       class: Utilization
        type: System
   component: Disk
 host labels: _os=linux freebsd
chart labels: mount_point=!/dev !/dev/* !/run !/run/* *
         calc: $used * 100 / ($avail + $used)
        units: %
        every: 1m
         warn: $this > (($status >= $WARNING ) ? (80) : (90))
         crit: ($this > (($status == $CRITICAL) ? (90) : (98))) && $avail < 5
        delay: up 1m down 15m multiplier 1.5 max 1h
      summary: Disk ${label:mount_point} space usage
         info: Total space utilization of disk ${label:mount_point}
           to: sysadmin

    template: disk_inode_usage
          on: disk.inodes
       class: Utilization
        type: System
   component: Disk
 host labels: _os=linux freebsd
chart labels: mount_point=!/dev !/dev/* !/run !/run/* *
        calc: $used * 100 / ($avail + $used)
       units: %
       every: 1m
        warn: $this > (($status >= $WARNING)  ? (80) : (90))
        crit: $this > (($status == $CRITICAL) ? (90) : (98))
       delay: up 1m down 15m multiplier 1.5 max 1h
     summary: Disk ${label:mount_point} inode usage
        info: Total inode utilization of disk ${label:mount_point}
          to: sysadmin
