repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-json
      - id: check-yaml
        exclude: |
          (?x)^(edge-server/templates/static-ip-config.yml|
                edge-server/templates/opt/stacks/netdata/docker-compose.yml
          )$
      - id: end-of-file-fixer
      - id: no-commit-to-branch
      - id: trailing-whitespace
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline', '--exclude-lines', '/etc/passwd']
  - repo: https://github.com/ansible/ansible-lint.git
    rev: v6.20.0
    hooks:
      - id: ansible-lint
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.5.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies:
          - '@commitlint/config-conventional'
          - '@commitlint/ensure'
          - 'commitlint-plugin-function-rules'
