- name: Update apt cache
  become: true
  ansible.builtin.apt:
    cache_valid_time: "{{ cache_valid_time }}"
    update_cache: true

- name: Install packages
  become: true
  with_items: "{{ apt_packages }}"

  ansible.builtin.apt:
    cache_valid_time: "{{ cache_valid_time }}"
    name: "{{ item }}"
    update_cache: true

- name: Enable and start systemd-timesyncd
  become: true
  ansible.builtin.systemd:
    name: systemd-timesyncd
    enabled: true
    state: started

- name: Check if timedatectl is available
  become: true
  ansible.builtin.command: which timedatectl
  register: timedatectl_result
  changed_when: false
  failed_when: timedatectl_result.rc != 0

- name: Enable NTP with timedatectl
  become: true
  ansible.builtin.command: timedatectl set-ntp true
  when: timedatectl_result.rc == 0

- name: Ensure the AWS CLI installer directory exists
  become: true
  ansible.builtin.file:
    path: "/opt/awscli"
    state: directory
    mode: "0755"

- name: Download and unzip AWS CLI Installer
  become: true
  ansible.builtin.unarchive:
    src: "https://awscli.amazonaws.com/awscli-exe-linux-{{ arch }}-{{ awscli_version }}.zip"
    dest: "/opt/awscli"
    remote_src: true
    creates: "/opt/awscli/aws/install"

- name: Install AWS CLI if not already installed
  become: true
  ansible.builtin.command: "/opt/awscli/aws/install"
  args:
    creates: /usr/local/bin/aws

- name: Check if reboot is required
  changed_when: reboot_required.stat.exists
  notify: Reboot
  register: reboot_required
  ansible.builtin.stat:
    get_checksum: false
    path: /var/run/reboot-required

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
