- name: Update apt cache
  become: true
  ansible.builtin.apt:
    cache_valid_time: "{{ cache_valid_time }}"
    update_cache: true

- name: Install packages
  become: true
  with_items: "{{ apt_packages }}"

  ansible.builtin.apt:
    cache_valid_time: "{{ cache_valid_time }}"
    name: "{{ item }}"
    update_cache: true

- name: Ensure the AWS CLI installer directory exists
  become: true
  ansible.builtin.file:
    path: "/opt/awscli"
    state: directory
    mode: "0755"

- name: Download and unzip AWS CLI Installer
  become: true
  register: awscli
  ansible.builtin.unarchive:
    src: "https://awscli.amazonaws.com/awscli-exe-linux-{{ arch }}-{{ awscli_version }}.zip"
    dest: "/opt/awscli"
    remote_src: true

- name: Install aws cli
  when: awscli is changed
  become: true
  ansible.builtin.shell: "/opt/awscli/aws/install"

- name: Check if reboot is required
  changed_when: reboot_required.stat.exists
  notify: Reboot
  register: reboot_required
  ansible.builtin.stat:
    get_checksum: false
    path: /var/run/reboot-required

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Debug
  ansible.builtin.debug:
    msg: "{{ awscli.changed }}"

