- name: Update apt cache and install prerequisite packages for docker
  become: true
  with_items: "{{ docker_prerequisite_packages }}"
  ansible.builtin.apt:
    name: "{{ item }}"
    update_cache: true
    cache_valid_time: "{{ cache_valid_time }}"

- name: Create keyrings directory if it does not exist
  become: true
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '755'

- name: Download docker gpg key
  become: true
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /tmp/docker.gpg
    mode: '644'

- name: Add gpg key to keyrings
  become: true
  ansible.builtin.command:
    cmd: gpg --dearmor -o /etc/apt/keyrings/docker.gpg /tmp/docker.gpg
    creates: /etc/apt/keyrings/docker.gpg

- name: Ensure docker.gpg has read permission
  become: true
  ansible.builtin.file:
    path: /etc/apt/keyrings/docker.gpg
    mode: '644'

- name: Add docker repository to apt sources
  become: true
  ansible.builtin.apt_repository:
    state: present  # default
    repo: "deb [arch={{ deb_arch }} signed-by=/etc/apt/keyrings/docker.gpg]
      https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    filename: docker

- name: Install packages
  become: true
  when: not docker_version
  notify:
    - Restart docker daemon
  with_items:
    - containerd.io
    - docker-buildx-plugin
    - docker-ce
    - docker-ce-cli
  ansible.builtin.apt:
    name: "{{ item }}"
    cache_valid_time: "{{ cache_valid_time }}"

- name: Create docker group
  become: true
  ansible.builtin.group:
    name: docker
    state: present

- name: Add user to the docker group
  become: true
  ansible.builtin.user:
    append: true
    groups: docker
    name: "{{ ansible_user_id }}"


- name: Check if reboot is required
  changed_when: reboot_required.stat.exists
  notify: Reboot
  register: reboot_required
  ansible.builtin.stat:
    get_checksum: false
    path: /var/run/reboot-required

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
