- name: Create service directory
  become: true
  ansible.builtin.file:
    path: /greengrass
    state: directory
    mode: '0755'

- name: Create public directories if it does not exist
  become: true
  with_items:
    - /config
    - /video
    - /deployment/videos
    - /models
    - /images
    - /logs
    - /ftp-data
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0777'

- name: Create greengrass group
  become: true
  ansible.builtin.group:
    name: "{{ greengrass_group }}"
    state: present

- name: Create greengrass user
  become: true
  ansible.builtin.user:
    groups:
      - "{{ greengrass_group }}"
      - docker
    name: "{{ greengrass_user }}"

# FIXME gg_lambda docker socket permission denied and remove sudo ability
- name: Add greengrass user to the docker group
  become: true
  ansible.builtin.user:
    append: true
    groups: docker
    name: "{{ ansible_user_id }}"

- name: Add greengrass user to sudoers
  become: true
  ansible.builtin.lineinfile:
    path: "/etc/sudoers.d/{{ greengrass_user }}"
    line: "{{ greengrass_user }} ALL=(ALL) NOPASSWD: ALL"
    state: present
    mode: "0440"
    create: true
    validate: 'visudo -cf %s'

- name: Set includedir in sudoers
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/sudoers
    line: "#includedir /etc/sudoers.d"
    state: present
    validate: "/usr/sbin/visudo -cf %s"

- name: Add Python repository to the apt sources
  become: true
  ansible.builtin.apt_repository:
    repo: "ppa:deadsnakes/ppa"
    state: present
  environment:
    DEBIAN_FRONTEND: noninteractive

- name: Add Greengrass runtime
  become: true
  with_items:
    - python3.8
    - python3.8-distutils
    - python3-pip
  ansible.builtin.apt:
    name: "{{ item }}"
    cache_valid_time: "{{ cache_valid_time }}"

- name: Get pip for python3.8
  ansible.builtin.get_url:
    url: https://bootstrap.pypa.io/get-pip.py
    dest: /tmp/get-pip.py
    mode: '0664'
  register: get_pip

- name: Install pip for python3.8  # noqa command-instead-of-shell no-handler
  failed_when: install_pip.rc != 0
  become: true
  ansible.builtin.shell:
    cmd: /usr/bin/python3.8 /tmp/get-pip.py --break-system-packages --ignore-installed
  register: install_pip
  when: get_pip is changed

- name: Remove packages installed by debian for ubuntu 24
  become: true
  with_items:
    - python3-urllib3
    - python3-attrs
  ansible.builtin.apt:
    name: "{{ item }}"
    state: absent
  # Task specific to Ubuntu 24.04
  when: ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_version'] is version('24.04', '==')

- name: Add Greengrass runtime dependencies
  become: true
  changed_when: '"Installing collected packages" in is_gg_runtime_dep_installed.stdout'
  register: is_gg_runtime_dep_installed
  with_items:
    - awscli
    - greengrasssdk
    - attrs==23.1.0
    - python-dotenv
    - requests
    - retry
    - fabric
    - cffi
  ansible.builtin.command: "python3.8 -m pip install --ignore-installed {{ item }}"

- name: Download greengrass-core
  ansible.builtin.get_url:
    url: "https://d1onfpft10uf5o.cloudfront.net/greengrass-core/downloads/{{ greengrass_version }}/greengrass-linux-{{ gg_arch }}-{{ greengrass_version }}.tar.gz"
    dest: "{{ ansible_env.HOME }}/opt/greengrass-linux-{{ gg_arch }}-{{ greengrass_version }}.tar.gz"
    mode: "0664"

- name: Unpack greengrass-core
  become: true
  ansible.builtin.unarchive:
    src: "{{ ansible_env.HOME }}/opt/greengrass-linux-{{ gg_arch }}-{{ greengrass_version }}.tar.gz"
    dest: /greengrass
    remote_src: true
    extra_opts:
      - --strip-components=1

- name: Download greengrass certs
  become: true
  ansible.builtin.get_url:
    url: https://www.amazontrust.com/repository/AmazonRootCA1.pem
    dest: /greengrass/certs/root.ca.pem
    mode: "0644"

- name: Copy greengrass.service to the /etc/systemd/system/
  become: true
  notify:
    - Enable greengrass.service
  ansible.builtin.copy:
    src: files/etc/systemd/system/greengrass.service
    dest: /etc/systemd/system/greengrass.service
    mode: "0644"

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
