Vagrant.configure("2") do |config|

  config.vm.define "focal64", primary: true do |c|
    c.vm.box = "ubuntu/focal64"
    config.vm.box_version = "20230619.0.0"
  end

 # https://developer.hashicorp.com/vagrant/docs/providers/virtualbox/configuration
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 4086
    vb.cpus = 1
  end

end
