FROM netdata/netdata:v1.47

RUN apt-get update && apt-get install -y python3-pip nano \
    && pip install jetson-stats==4.2.12 --break-system-packages && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
